<?php
/**
 * Featured Products Slider
 */
?>
<?php
    $_productCollection = $this->getLoadedProductCollection();
?>
<?php if ($_productCollection && ($collectionSize = $this->getCollectionCount())): ?>
<?php
    $_helper = $this->helper('catalog/output');
    $theme = $this->helper('ultimo');
    $helperLabels = $this->helper('ultimo/labels');
    $helpImg = $this->helper('infortis/image');
    $helpTemplate = $this->helper('ultimo/template');

    $sliderClasses = '';
    $wrapperClasses = '';
    $hash = $this->getFrontendHash();
    $sliderId = "itemslider-featured-{$hash}";


    //
    // Product image configuration
    // ----------------------------------------------

    // Product image dimensions
    $paramImgWidth = $this->getData('img_width');
    $paramImgHeight = $this->getData('img_height');
    if ($paramImgWidth || $paramImgHeight)
    {
        // Use values from params
        $imgWidth = intval($paramImgWidth);
        $imgHeight = intval($paramImgHeight);
    }
    else
    {
        // Set default values
        $imgWidth = 170;
        $imgHeight = 170;

        // If none of the image dimension parameters is set
        // then for backward compatibility check the obsolete option.
        if ($theme->getCfg('category/aspect_ratio'))
        {
            $imgHeight = null; // If keep aspect ratio, delete the height
        }
    }

    // If value equals zero or not set, replace it with null
    if (empty($imgWidth))
    {
        $imgWidth = null;
    }
    if (empty($imgHeight))
    {
        $imgHeight = null;
    }

    // Alternative product image
    $showAltImage = $theme->getCfg('category/alt_image');

    //
    // Slider configuration
    // ----------------------------------------------

    // Single item
    if ($collectionSize == 1)
    {
        $sliderClasses .= ' single-item';
    }

    // Breakpoints
    $breakpoints = $this->getData('breakpoints');
    if ($breakpoints === null)
    {
        $breakpoints = '[0, 1], [320, 2], [480, 3], [768, 4], [992, 5], [1200, 6]';
    }

    // Responsive mode on/off and number of items
    $isResponsive = $this->getData('is_responsive');
    if ($isResponsive === null)
    {
        $isResponsive = true;
    }

    if (!$isResponsive)
    {
        $showItems = $this->getData('show_items');
        if (!$showItems)
        {
            $showItems = 5;
        }
    }
    else
    {
        $sliderClasses .= ' itemslider-responsive';
    }

    // Timeout (automatic scrolling)
    $timeout = $this->getData('timeout');
    if ($timeout === null)
    {
        $timeout = intval($theme->getCfg('product_slider/timeout'));
    }
    else
    {
        $timeout = intval($timeout);
    }


    // Number of items that should move on scroll
    $move = $this->getData('move');
    if ($move === null)
    {
        $move = 0;
    }
    else
    {
        $move = intval($move);
    }

    // Pagination
    $pagination = $this->getData('pagination');

    // Loop
    $loop = $this->getData('loop');
    if ($loop === null)
    {
        $loop = $theme->getCfg('product_slider/loop');
    }

    // Speed (arrows / touch swipe)
    $speed = intval($theme->getCfg('product_slider/speed'));

    // Speed (automatic scrolling / pagination)
    $autoSpeed = intval($theme->getCfg('product_slider/auto_speed'));

    // Pause on mouse hover
    $pause = $theme->getCfg('product_slider/pause');

    // Lazy loading
    $lazy = $theme->getCfg('product_slider/lazy');

    //
    // Grid configuration
    // ----------------------------------------------

    // Rows
    $numberOfRows = $this->getData('rows');
    if (empty($numberOfRows))
    {
        $numberOfRows = 1;
    }
    else
    {
        $numberOfRows = intval($numberOfRows);
    }
    
    // Display as thumbnails
    $thumbnails = $this->getData('thumbnails');
    if (!empty($thumbnails))
    {
        $thumbnails = strtolower($thumbnails);

        if ($thumbnails === 'xs')
        {
            if ($paramImgWidth === null && $paramImgHeight === null)
            {
                $imgWidth = 80;
                $imgHeight = 80;
            }
        }
        elseif ($thumbnails === 's')
        {
            if ($paramImgWidth === null && $paramImgHeight === null)
            {
                $imgWidth = 100;
                $imgHeight = 100;
            }
        }
        elseif ($thumbnails === 'm')
        {
            if ($paramImgWidth === null && $paramImgHeight === null)
            {
                $imgWidth = 150;
                $imgHeight = 150;
            }
        }
        elseif ($thumbnails === 'l')
        {
            if ($paramImgWidth === null && $paramImgHeight === null)
            {
                $imgWidth = 200;
                $imgHeight = 200;
            }
        }
        else
        {
            // Set defaults
            $thumbnails = 's';
            if ($paramImgWidth === null && $paramImgHeight === null)
            {
                $imgWidth = 100;
                $imgHeight = 100;
            }
        }

        // Note that in Mage2 these classes are prefixed with "items-grid" instead of "products-grid"
        $wrapperClasses .= ' products-grid-thumbnails products-grid-thumbnails-' . $thumbnails;
    }

    // Size of item's elements
    $size = $this->getData('size');
    if ($size !== null)
    {
        // For backward compatibility, convert old values to new values
        if ($size === 'size-s') 
        {
            $size = 's';
        }
        elseif ($size === 'size-xs')
        {
            $size = 'xs';
        }

        $size = strtolower($size);
        $wrapperClasses .= ' size-' . $size;
    }
    else
    {
        if (isset($showItems))
        {
            if ($showItems >= 8)
            {
                $wrapperClasses .= ' size-xs';
            }
            elseif ($showItems >= 6)
            {
                $wrapperClasses .= ' size-s';
            }
        }
    }

    // Align elements to the center 
    if ($this->getData('centered'))
    {
        $wrapperClasses .= ' centered';
    }

    // Equal height of items
    if ($this->getData('equal_height'))
    {
        $wrapperClasses .= ' equal-height';
    }

    // Hide product labels
    $hideLabels = $this->getData('hide_labels');

    // Hide add-to links
    $hideAddToLinks = $this->getData('hide_addto_links');

    // Hide name
    $hideName = $this->getData('hide_name');

    // Hide rating
    $hideRating = $this->getData('hide_rating');

    // Hide price
    $hidePrice = $this->getData('hide_price');

    // Hide "Add to cart" button
    $hideAddToCart = $this->getData('hide_button');

    // Product labels classes
    $wrapperClasses .= ' ' . $helperLabels->getLabelsClasses();
?>
<strong class="section-title padding-right"><?php echo $this->getBlockName(); ?></strong>
<div class="itemslider-wrapper slider-arrows1 slider-arrows1-pos-top-right slider-pagination1">
    <div id="<?php echo $sliderId; ?>" class="itemslider<?php if($sliderClasses) echo $sliderClasses; ?> products-grid<?php if($wrapperClasses) echo $wrapperClasses; ?>">
    <?php
        $i = 0;
    ?>
    <?php foreach ($_productCollection as $_product): ?>

        <?php if ($numberOfRows > 1 && $i++ % $numberOfRows == 0): // Start a group of items (a slide) ?>
            <div class="items-group">
        <?php endif; ?>

        <div class="item">

            <div class="product-item-img product-image-wrapper" style="max-width:<?php echo $imgWidth; ?>px;">
            
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true); ?>" class="product-image">
                    
                    <?php if ($lazy && $numberOfRows < 2): ?>
                        <img class="lazyOwl" data-src="<?php echo $helpImg->getImg($_product, $imgWidth, $imgHeight, 'small_image'); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true); ?>" />
                    <?php else: ?>
                        <img src="<?php echo $helpImg->getImg($_product, $imgWidth, $imgHeight, 'small_image'); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true); ?>" />
                    <?php endif; ?>

                    <?php if ($showAltImage): ?>
                        <?php echo $theme->getAltImgHtml($_product, $imgWidth, $imgHeight); ?>
                    <?php endif; ?>

                    <?php if (!$hideLabels): ?>
                        <?php echo $helperLabels->getLabels($_product); ?>
                    <?php endif; ?>
                </a>

                <?php if (!$hideAddToLinks): ?>
                <?php //Add-to links
                    if ($theme->getCfg('category_grid/display_addtolinks') != 0 
                        && $theme->getCfg('category_grid/addtolinks_simple'))
                    {
                        if ($theme->getCfg('category_grid/display_addtolinks') == 1) //Display on hover
                        {
                            echo $helpTemplate->getCategoryAddtoLinksIcons(
                            $_product, $this->getAddToCompareUrl($_product), 'addto-links-icons addto-onimage onhover');
                        }
                        else //Always display
                        {
                            echo $helpTemplate->getCategoryAddtoLinksIcons(
                            $_product, $this->getAddToCompareUrl($_product), 'addto-links-icons addto-onimage');
                        }
                    }
                ?>
                <?php endif; ?>
                
            </div> <!-- end: product-item-img -->
            <div class="product-item-details">

                <?php if (!$hideName): ?>
                    <strong class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></strong>
                <?php endif; ?>

                <?php if (!$hideRating): ?>
                    <?php if($_product->getRatingSummary()): ?>
                        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                    <?php endif; ?>
                <?php endif; ?>

                <?php if (!$hidePrice): ?>
                    <?php echo $this->getPriceHtml($_product, true, $hash) ?>
                <?php endif; ?>

                <div class="actions">
                    <?php if (!$hideAddToCart): ?>
                        <?php if(!$_product->canConfigure() && $_product->isSaleable()): ?>
                            <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                        <?php elseif($_product->getStockItem() && $_product->getStockItem()->getIsInStock()): ?>
                            <a title="<?php echo $this->__('View Details') ?>" class="button btn-cart" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a>
                        <?php else: ?>
                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>
                    <?php endif; ?>

                    <?php //Add-to links
                    if ($theme->getCfg('category_grid/display_addtolinks') != 0 && !$theme->getCfg('category_grid/addtolinks_simple'))
                    {
                        if ($theme->getCfg('category_grid/display_addtolinks') == 1) //Display on hover
                            echo $helpTemplate->getCategoryAddtoLinks($_product, $this->getAddToCompareUrl($_product), 'addto-gaps-right addto-texticons display-onhover');
                        else //Always display
                            echo $helpTemplate->getCategoryAddtoLinks($_product, $this->getAddToCompareUrl($_product), 'addto-gaps-right addto-texticons');
                    }
                    ?>
                </div>

            </div> <!-- end: product-item-details -->
            
        </div>

        <?php if ($numberOfRows > 1 && ($i % $numberOfRows == 0 || $i == $collectionSize)): // Close a group of items (a slide) ?>
            </div> <!-- end: items-group -->
        <?php endif ?>

    <?php endforeach; ?>
    </div> <!-- end: itemslider -->
</div> <!-- end: itemslider-wrapper -->
<script type="text/javascript">
//<![CDATA[
    jQuery(function($) {
        
        var owl = $('#<?php echo $sliderId; ?>');
        owl.owlCarousel({

        <?php if ($lazy): ?>
            lazyLoad: true,
        <?php endif; ?>

        <?php if(!$isResponsive): ?>
            responsive: false,
            items: <?php echo $showItems; ?>,
        <?php else: ?>
            itemsCustom: [ <?php echo $breakpoints; ?> ],
            responsiveRefreshRate: 50,
        <?php endif; ?>

        <?php if ($speed): ?>
            slideSpeed: <?php echo $speed; ?>,
        <?php endif; ?>

        <?php if ($autoSpeed): ?>
            paginationSpeed: <?php echo $autoSpeed; ?>,
        <?php endif; ?>

        <?php if ($move !== 1): ?>
            scrollPerPage: true,
        <?php endif; ?>

        <?php if ($timeout): ?>
            autoPlay: <?php echo $timeout; ?>,
        <?php endif; ?>

        <?php if ($pause): ?>
            stopOnHover: true,
        <?php endif; ?>

        <?php if ($loop): ?>
            rewindNav: true,
            rewindSpeed: 600,
        <?php else: ?>
            rewindNav: false,
        <?php endif; ?>

        <?php if ($pagination): ?>
            pagination: true,
        <?php else: ?>
            pagination: false,
        <?php endif; ?>

            navigation: true,
            navigationText: false

        }); //end: owl

    });
//]]>
</script>
<?php endif; ?>
